# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

environment:
  global:
    DB_NAME: f1db
    DB_USER: user
    DB_PASSWORD: password
    PURPLE_SECTOR_CONFIG: resources/test/windows/config.yml

install:
  - docker version
  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe"
  - rustup-init.exe -y --default-host i686-pc-windows-msvc
  - SET PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V
  - docker run -e MYSQL_DATABASE=${DB_NAME} -e MYSQL_USER=${DB_USER} -e MYSQL_PASSWORD=${DB_PASSWORD} -p "3306:3306" -d --rm thibaultcne/purple-sector:db-test --default-authentication-plugin=mysql_native_password
  - docker run -d -p "6379:6379" --rm docker.dragonflydb.io/dragonflydb/dragonfly:v1.16.1
  - sleep 4

test_script:
  # Run the tests
  - echo ${PURPLE_SECTOR_CONFIG}
  - cargo test --tests

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

branches:
  only:
    # Release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false
