[workspace]
members = ["crates/*", "bin/*", "tests-integration"]
resolver = "2"

[workspace.dependencies]
rocket = { version = "0.5.0", features = ["json"] }
chrono = { version = "0.4.31", features = ["serde"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.64"
dotenvy = "0.15.7"
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = { version = "2.0.48", features = ["parsing"] }
sea-query = { version = "0.30.7", features = ["backend-mysql"] }
r2d2 = "0.8.10"
mysql = { version = "25.0.0", default-features = false, features = ["minimal"] }
mysql_common = { version = "0.32.2", default-features = false, features = ["chrono", "derive", "bigdecimal"] }
redis = "0.25.3"
