[package]
name = "f1-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.31" }
reqwest = { version = "0.11.3", features = ["blocking"] }
scraper = "0.18.1"
