[workspace]
members = ["crates/*", "bin/*"]
resolver = "2"

[workspace.dependencies]
# Local crates
api-lib = { path = "./crates/api", version = "0.1.0" }
application = { path = "./crates/application", version = "0.1.0" }
derives = { path = "./crates/derives", version = "0.1.0" }
infrastructure = { path = "./crates/infrastructure", version = "0.1.0" }
shared = { path = "./crates/shared", version = "0.1.0" }

# External crates
rocket = { version = "0.5.0", features = ["json"] }
chrono = { version = "0.4.31", features = ["serde"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.64"
dotenvy = "0.15.7"
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = { version = "2.0.48", features = ["parsing"] }
sea-orm = { version = "^0.12.0", features = ["sqlx-mysql", "macros"] }
sea-query = "0.30.7"
sea-query-diesel = { version = "0.1.0", features = [
    "mysql",
    "with-chrono",
    "with-json",
    "with-uuid",
    "with-time",
    "with-rust_decimal",
    "with-bigdecimal",
] }
r2d2 = "0.8.10"
diesel = { version = "2.1.0", features = ["mysql", "chrono", "r2d2"] }
