---
database:
  name: f1db
  hostname: 127.0.0.1
  port: 3306
  user: user
  password: password

cache:
  hostname: 127.0.0.1
  port: 6379

middlewares:
  - rate_limiter:
      enabled: true
      requests: 100
      seconds: 60
      type: sliding_window
