---
database:
  name: f1db
  hostname: database
  port: 3306
  user: user
  password: password

cache:
  hostname: dragonfly
  port: 6379

middlewares:
  - graphiql:
      enabled: true
      route: /
