---
database:
  name: f1db
  hostname: database
  port: 3306
  user: user
  password: password

cache:
  hostname: dragonfly
  port: 6379

middlewares:
  - rate_limiter:
      enabled: false
      requests: 100
      seconds: 60
      type: sliding_window
  - cache:
      enabled: false
      # Time to live in seconds
      ttl: 3600
