---
services:
  database:
    build:
      context: resources/dockerfiles/database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.16.1
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data

volumes:
  dragonflydata:
