---
version: "3"

dotenv: [".env"]

tasks:
  swagger_up:
    cmds:
      - docker run -d -p 8080:80 --name swagger_rust_race_engine swaggerapi/swagger-editor:next-v5
    silent: true
  swagger_down:
    cmds:
      - docker stop swagger_rust_race_engine
      - docker rm swagger_rust_race_engine
    silent: true
  db_up:
    cmds:
      - docker run
        --name=rust_race_engine
        -d
        -p 3306:3306
        -v $(pwd)/db/f1db.sql:/docker-entrypoint-initdb.d/dump.sql
        -e MYSQL_DATABASE="$MYSQL_DATABASE"
        -e MYSQL_USER="$MYSQL_USER"
        -e MYSQL_PASSWORD="$MYSQL_PASSWORD"
        mysql/mysql-server:8.0.32
    silent: true
  db_down:
    cmds:
      - docker stop rust_race_engine
      - docker rm rust_race_engine
    silent: true
