[package]
name = "purple-sector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket.workspace = true
dotenvy.workspace = true
mysql.workspace = true
chrono.workspace = true
log.workspace = true
tokio.workspace = true

api-lib = { path = "../../crates/api" }
infrastructure = { path = "../../crates/infrastructure" }
logger = { path = "../../crates/logger" }
shared = { path = "../../crates/shared" }

[dev-dependencies]
axum.workspace = true
tower.workspace = true
serde_json.workspace = true

http-body-util = "0.1.0"
