[package]
name = "api-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket.workspace = true
serde.workspace = true
r2d2.workspace = true
serde_json.workspace = true
mysql.workspace = true
chrono.workspace = true
redis.workspace = true

application = { path = "../application" }
infrastructure = { path = "../infrastructure" }
shared = { path = "../shared" }
