---
name: F1 database updater
on: workflow_dispatch

jobs:
  caller:
    runs-on: ubuntu-latest

    outputs:
      run_id: ${{ steps.return_dispatch.outputs.run_id }}

    steps:
      - name: Dispatch an action and get the run ID
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.UPDATER_PAT }}
          ref: main
          repo: f1-data-updater
          owner: race-tech
          workflow: main.yml
      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: Codex-/await-remote-run@v1.0.0
        with:
          token: ${{ secrets.UPDATER_PAT }}
          repo: f1-data-updater
          owner: race-tech
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
          run_timeout_seconds: 300 # Optional
          poll_interval_ms: 5000 # Optional

  updater:
    runs-on: ubuntu-latest
    needs: caller

    steps:
      - name: Check if a new artifact has been created
        id: check
        uses: thibault-cne/check-artifacts@v1
        with:
          token: ${{ secrets.UPDATER_PAT }}
          repo: f1-data-updater
          owner: race-tech
          run_id: ${{ needs.caller.outputs.run_id }}
          name: f1db.sql.gz

      - name: Dowload SQL dump
        if: steps.check.outputs.artifact_exists == 'true'
        uses: actions/download-artifact@v4
        with:
          name: f1db.sql.gz
          github-token: ${{ secrets.UPDATER_PAT }}
          repository: race-tech/f1-data-updater
          run-id: ${{ needs.caller.outputs.run_id }}

      - name: Test
        run: echo "continuing..."
